name: pl_flow
description:  Lightweight, Flutter-friendly reactive flows for state and event streams. 
version: 1.1.0
homepage: https://github.com/NexPlugs/pl_flow
repository: https://github.com/NexPlugs/pl_flow

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  async: ^2.13.0
  collection: ^1.19.1
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  synchronized: ^3.4.0
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass

topics:
  - flow
  - state
  - stream
  - builder